### ISSUE TITLE
Research: How can we deploy a Dockerized Flask application and to what service?

### ISSUE THREAD

**Issue by Brett-Mulder** [fuas-dverse/ticket-system-agent#16]
# Description
We want to deploy a Dockerized Flask application to a certain service. We don't know yet which service this is going to be, so we need to research this, what is the best option.

# Realise as an expert

Library:
- [ ] Literature study
- [x] Available product analysis

Workshop:
- [x] Prototyping

Showroom:
- [ ] Static program analysis

![Image](https://github.com/fuas-dverse/ticket-system-agent/assets/111641213/35b19af5-e428-4344-a362-b3cfff8ef5f7)

**Comment by RenoMuijsenberg** [comment]
This morning we discussed together about this problem and decided that it would be good to trigger a CI/CD pipeline based on a push to a folder. This will leave the folder structure in tact but still be able to sperate them!
